# Generated by Django 4.0.3 on 2022-07-31 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id_dataset', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Dataset',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id_content', models.AutoField(primary_key=True, serialize=False)),
                ('c', models.CharField(max_length=1000)),
                ('a1', models.FloatField(blank=True, null=True)),
                ('a2', models.FloatField(blank=True, null=True)),
                ('a3', models.FloatField(blank=True, null=True)),
                ('a4', models.FloatField(blank=True, null=True)),
                ('a5', models.FloatField(blank=True, null=True)),
                ('a6', models.FloatField(blank=True, null=True)),
                ('a7', models.FloatField(blank=True, null=True)),
                ('a8', models.FloatField(blank=True, null=True)),
                ('a9', models.FloatField(blank=True, null=True)),
                ('id_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict.dataset')),
            ],
            options={
                'verbose_name_plural': 'Content',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id_attribute', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('id_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict.dataset')),
            ],
            options={
                'verbose_name_plural': 'Attribute',
            },
        ),
    ]
